"""50 curated UGC content items with gold labels for brand-safe ad review."""

from typing import Any, Dict, List

CONTENT_ITEMS: List[Dict[str, Any]] = [
    # Easy items
    {
        "content_id": "easy_001",
        "content_text": "Just made the most amazing chocolate chip cookies! 🍪 Recipe in bio. #baking #homemade #foodie",
        "content_type": "caption",
        "platform": "instagram",
        "difficulty": "easy",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "gold_age_rating": "ALL_AGES",
        "context_layer_1": "Account @bakingwithbella, created 2019-03-14, 45K followers. Food/recipe niche. Zero content warnings. Verified food blogger with brand partnerships (KitchenAid, King Arthur Flour).",
        "context_layer_2": "No community reports. No cross-platform flags. Content pattern: 98% baking/recipe posts. Engagement rate consistent with organic food content creators.",
        "notes": "Clearly safe lifestyle content",
    },
    {
        "content_id": "easy_002",
        "content_text": "Morning run done! 5 miles before sunrise. Nothing beats that feeling 🏃‍♂️ #fitness #running #motivation",
        "content_type": "post",
        "platform": "x",
        "difficulty": "easy",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "gold_age_rating": "ALL_AGES",
        "context_layer_1": "Account @mileswithmike, created 2020-06-01, 22K followers. Fitness influencer, marathon runner. Clean moderation history — zero warnings, zero strikes.",
        "context_layer_2": "No community reports. No cross-platform flags. Content pattern: 100% fitness/wellness posts. Frequently tagged by running shoe brands for ambassador content.",
        "notes": "Fitness/wellness content, universally brand-safe",
    },
    {
        "content_id": "easy_003",
        "content_text": "I want to f***ing kill my sister she ate my last slice of pizza 😤😤😤",
        "content_type": "post",
        "platform": "x",
        "difficulty": "easy",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_PROFANITY",
        "gold_garm_category": "GARM_OBSCENITY_PROFANITY",
        "gold_risk_level": "HIGH",
        "gold_age_rating": "MATURE",
        "context_layer_1": "Account @jess_2007x, created 2024-01-10, 340 followers. Account age: 4 months. 2 prior warnings for profanity violations. No verified identity.",
        "context_layer_2": "3 community reports for abusive language in past 30 days. No cross-platform flags. Content pattern: frequent emotional outbursts with profanity; no sustained harassment pattern.",
        "notes": "Profanity + violent language, clear reject",
    },
    {
        "content_id": "easy_004",
        "content_text": "Buy cheap Xanax no prescription needed!! DM for prices. Discreet shipping worldwide 💊",
        "content_type": "bio",
        "platform": "instagram",
        "difficulty": "easy",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_ILLEGAL",
        "gold_garm_category": "GARM_CRIME_HARMFUL",
        "gold_risk_level": "CRITICAL",
        "gold_age_rating": "ADULT",
        "context_layer_1": "Account @discountpharma_rx, created 2024-03-28, 12 followers. Flagged by DEA automated watchlist. Account matches known pharmacy spam signature. 4 prior accounts banned for identical activity.",
        "context_layer_2": "87 community reports in 72 hours. Cross-platform flags: identical bio text detected on 6 other platforms. Linked to known international prescription drug spam ring per Trust & Safety intel.",
        "notes": "Illegal drug sales, immediate reject",
    },
    {
        "content_id": "easy_005",
        "content_text": "Sunset hike with the crew 🌅 Nature is the best therapy. #hiking #outdoors #adventure",
        "content_type": "caption",
        "platform": "instagram",
        "difficulty": "easy",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "gold_age_rating": "ALL_AGES",
        "context_layer_1": "Account @trailsandtales, created 2018-11-20, 67K followers. Travel/outdoor niche. Brand ambassador for REI and Osprey. Zero moderation actions.",
        "context_layer_2": "No community reports. No cross-platform flags. Content pattern: 95% nature/hiking photography. High engagement from outdoor recreation communities.",
        "notes": "Outdoor/nature content, universally safe",
    },
    {
        "content_id": "easy_006",
        "content_text": "GRAPHIC: Compilation of the most brutal street fight knockouts 2024 💀 LIKE AND SUBSCRIBE",
        "content_type": "caption",
        "platform": "youtube",
        "difficulty": "easy",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_VIOLENCE",
        "gold_garm_category": "GARM_DEATH_INJURY",
        "gold_risk_level": "HIGH",
        "gold_age_rating": "MATURE",
        "context_layer_1": "Account @brutalKO_compilations, created 2023-08-05, 8.2K followers. Uploads exclusively gore and street fight compilations. 6 prior strikes for graphic violence.",
        "context_layer_2": "142 community reports in past 90 days. Cross-platform flags: identical content posted on 3 gore-sharing sites. Related accounts form a violence content network flagged by Trust & Safety.",
        "notes": "Explicit violence, clear reject",
    },
    {
        "content_id": "easy_007",
        "content_text": "My dog learned to high-five today!! 🐾 Took 3 days of training but SO worth it #dogsofinstagram",
        "content_type": "reel",
        "platform": "instagram",
        "difficulty": "easy",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "gold_age_rating": "ALL_AGES",
        "context_layer_1": "Account @goldenpaws_max, created 2020-02-14, 112K followers. Pet influencer with brand partnerships (Chewy, BarkBox). Zero content warnings. Verified pet content creator.",
        "context_layer_2": "No community reports. No cross-platform flags. Content pattern: 100% pet training and dog lifestyle content. Consistent positive engagement metrics.",
        "notes": "Pet content, universally brand-safe",
    },
    {
        "content_id": "easy_008",
        "content_text": "These [ethnic slur] are ruining our country. Share if you agree. #deportthem",
        "content_type": "post",
        "platform": "x",
        "difficulty": "easy",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_HATE_SPEECH",
        "gold_garm_category": "GARM_HATE_SPEECH",
        "gold_risk_level": "CRITICAL",
        "gold_age_rating": "ADULT",
        "context_layer_1": "Account @patriotdefender1488, created 2023-05-12, 890 followers. Account suspended twice previously for hate speech. Affiliated with known hate group per SPLC watchlist integration.",
        "context_layer_2": "64 community reports in past 30 days. Cross-platform flags: banned from 3 other platforms for identical hate speech. Content pattern: 100% xenophobic and racially targeted posts.",
        "notes": "Explicit hate speech, immediate reject",
    },
    {
        "content_id": "easy_009",
        "content_text": "New study hack: Pomodoro technique changed my life 📚 25 min focus, 5 min break. Try it! #studytok",
        "content_type": "comment",
        "platform": "tiktok",
        "difficulty": "easy",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "gold_age_rating": "ALL_AGES",
        "context_layer_1": "Account @studywithsara, created 2022-09-01, 15K followers. Student account, university-verified (.edu email). Content exclusively education and study tips. Zero warnings.",
        "context_layer_2": "No community reports. No cross-platform flags. Content pattern: 100% study tips, productivity hacks, and exam prep content. Frequently shared in academic communities.",
        "notes": "Educational productivity content",
    },
    {
        "content_id": "easy_010",
        "content_text": "18+ ONLY 🔞 Full uncensored content available. DM me for access. New videos daily 😈",
        "content_type": "bio",
        "platform": "instagram",
        "difficulty": "easy",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_ADULT",
        "gold_garm_category": "GARM_ADULT_EXPLICIT",
        "gold_risk_level": "CRITICAL",
        "gold_age_rating": "ADULT",
        "context_layer_1": "Account @exclusive_content_xx, created 2024-02-15, 2.1K followers. Linked to known adult content distribution ring. Banned from 4 other platforms for ToS violations involving explicit material.",
        "context_layer_2": "210 community reports in 2 weeks. Cross-platform flags: identical account bio detected across 8 platforms. Network analysis links to 12 coordinated accounts in adult content spam operation.",
        "notes": "Explicit adult content solicitation",
    },

    # Medium items
    {
        "content_id": "med_001",
        "content_text": "Honestly the government is lying to us about everything. Wake up sheeple. Do your own research 🐑 #truth",
        "content_type": "post",
        "platform": "x",
        "difficulty": "medium",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_MISINFORMATION",
        "gold_garm_category": "GARM_SPAM_HARMFUL",
        "gold_risk_level": "MEDIUM",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @truthseeker_q, created 2021-07-19, 5.4K followers. Posts conspiracy-related content weekly. No verified sources ever cited. No professional or journalistic credentials on file.",
        "context_layer_2": "18 community reports for misinformation in past 60 days. Cross-platform flags: shares content from known disinformation domains. Content pattern: escalating anti-government rhetoric with zero sourcing.",
        "notes": "Conspiracy/misinformation framing, brand risk",
    },
    {
        "content_id": "med_002",
        "content_text": "POV: you're at a wine tasting in Tuscany 🍷 This Chianti is absolutely divine. #wine #travel #italy",
        "content_type": "caption",
        "platform": "instagram",
        "difficulty": "medium",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @sommelierlucia, created 2017-05-22, 89K followers. Certified sommelier (Court of Master Sommeliers, Level 3). Active partnership with Tuscany Wine Tourism Board.",
        "context_layer_2": "No community reports. No cross-platform flags. Content pattern: 90% professional wine education and travel. Engagement consistent with luxury travel and food creator norms.",
        "notes": "Alcohol in aspirational travel context — most brands approve",
    },
    {
        "content_id": "med_003",
        "content_text": "Unpopular opinion: abortion should be illegal in all cases. Fight me in the comments 👇",
        "content_type": "post",
        "platform": "reddit",
        "difficulty": "medium",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_CONTROVERSIAL",
        "gold_garm_category": "GARM_HATE_SPEECH",
        "gold_risk_level": "HIGH",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @firedup_opinions, created 2022-11-01, 3.8K followers. History of increasingly extreme political posts across multiple topics. Engagement-bait pattern detected (provocative framing + 'fight me').",
        "context_layer_2": "34 community reports in past 30 days for inflammatory content. Cross-platform flags: similar engagement-bait posts on 2 other platforms. Content pattern: no substantive discussion, optimized for outrage clicks.",
        "notes": "Highly divisive political/social topic, brand risk",
    },
    {
        "content_id": "med_004",
        "content_text": "My honest review of the new Call of Duty: the gunplay is insane 🔫 10/10 would recommend #gaming",
        "content_type": "post",
        "platform": "reddit",
        "difficulty": "medium",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "gold_age_rating": "ALL_AGES",
        "context_layer_1": "Account @gamer_dave_reviews, created 2019-08-15, 156K subscribers. Verified gaming channel. Consistent game review content across AAA titles. Zero content warnings or strikes.",
        "context_layer_2": "No community reports. No cross-platform flags. Content pattern: 100% game reviews and gameplay commentary. No real-world violence content; all references are to in-game mechanics.",
        "notes": "Gaming review — fictional violence in mainstream game context is brand-safe",
    },
    {
        "content_id": "med_005",
        "content_text": "Lost 30lbs in 30 days with this ONE weird trick doctors don't want you to know! Link in bio 🔥",
        "content_type": "caption",
        "platform": "instagram",
        "difficulty": "medium",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_MISINFORMATION",
        "gold_garm_category": "GARM_SPAM_HARMFUL",
        "gold_risk_level": "MEDIUM",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @slimfast_secrets, created 2023-04-10, 11K followers. Account sells unregulated dietary supplements via affiliate links. Multiple FTC complaints filed for deceptive advertising claims.",
        "context_layer_2": "52 community reports for misleading health claims. Cross-platform flags: identical weight-loss scam content on 4 platforms. Linked to supplement drop-shipping network flagged by consumer protection agencies.",
        "notes": "Health misinformation / predatory marketing pattern",
    },
    {
        "content_id": "med_006",
        "content_text": "Microdosing psilocybin has genuinely helped my anxiety more than any prescription. Anyone else? 🍄",
        "content_type": "post",
        "platform": "x",
        "difficulty": "medium",
        "gold_decision": "ESCALATE",
        "gold_iab_category": "IAB_DRUGS",
        "gold_garm_category": "GARM_CRIME_HARMFUL",
        "gold_risk_level": "MEDIUM",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @mindful_healing_journey, created 2021-03-08, 9.2K followers. Mental health advocate. Posts primarily about therapy, mindfulness, and anxiety management. First time mentioning any controlled substance.",
        "context_layer_2": "2 community reports on this specific post (substance mention). No prior reports on any other content. No cross-platform flags. Content pattern: 97% mental health support content; this post is an outlier.",
        "notes": "Illegal substance discussion but framed as mental health — escalate for human review",
    },
    {
        "content_id": "med_007",
        "content_text": "This politician is literally destroying democracy. I can't believe people still vote for this clown 🤡",
        "content_type": "comment",
        "platform": "youtube",
        "difficulty": "medium",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_CONTROVERSIAL",
        "gold_garm_category": "GARM_SPAM_HARMFUL",
        "gold_risk_level": "MEDIUM",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @politicalrage247, created 2022-06-30, 6.1K followers. Posts exclusively political attacks targeting officials across parties. No substantive policy discussion in post history.",
        "context_layer_2": "22 community reports for harassment and inflammatory rhetoric in past 60 days. Cross-platform flags: similar attack content posted on 2 other platforms. Content pattern: 100% negative political commentary, zero constructive engagement.",
        "notes": "Political attack content, brand risk regardless of target",
    },
    {
        "content_id": "med_008",
        "content_text": "Vegas baby!! Hit the jackpot at the Bellagio 🎰💰 Best weekend of my life #lasvegas #gambling",
        "content_type": "post",
        "platform": "instagram",
        "difficulty": "medium",
        "gold_decision": "ESCALATE",
        "gold_iab_category": "IAB_GAMBLING",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "MEDIUM",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @jake_adventures, created 2020-10-05, 1.8K followers. Personal travel account. First gambling-related post ever. Post history is vacation photos, restaurants, and sightseeing.",
        "context_layer_2": "No community reports. No cross-platform flags. Content pattern: casual travel documentation. This is the only gambling-related post among 400+ lifetime posts. No affiliate links or promotional patterns detected.",
        "notes": "Gambling content — acceptable for some brands, not others. Escalate.",
    },
    {
        "content_id": "med_009",
        "content_text": "Homemade kombucha tutorial! Fermentation is basically controlled bacteria growth 🦠 #health #diy",
        "content_type": "caption",
        "platform": "tiktok",
        "difficulty": "medium",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "gold_age_rating": "ALL_AGES",
        "context_layer_1": "Account @fermentation_lab, created 2019-12-01, 38K followers. Food science educator with M.S. in Nutrition Science. Content focuses on evidence-based food preparation and gut health.",
        "context_layer_2": "No community reports. No cross-platform flags. Content pattern: 95% food science education with cited sources. Regularly links peer-reviewed nutrition studies. Recognized by platform as credentialed health educator.",
        "notes": "Health/DIY food content, clearly safe",
    },
    {
        "content_id": "med_010",
        "content_text": "Pirated the new Marvel movie, quality is actually great. DM me for the link 🎬 #movies",
        "content_type": "post",
        "platform": "reddit",
        "difficulty": "medium",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_ILLEGAL",
        "gold_garm_category": "GARM_ONLINE_PIRACY",
        "gold_risk_level": "HIGH",
        "gold_age_rating": "ADULT",
        "context_layer_1": "Account @free_movies_daily, created 2024-01-20, 4.7K followers. Shares piracy links daily. Part of a coordinated piracy distribution network identified by platform Trust & Safety.",
        "context_layer_2": "96 community reports and 3 DMCA takedown notices in past 30 days. Cross-platform flags: identical piracy link-sharing detected on 5 other platforms. Network analysis links to 8 coordinated piracy accounts.",
        "notes": "Explicit copyright piracy promotion",
    },

    # Hard items
    {
        "content_id": "hard_001",
        "content_text": "As a nurse, I see patients die from gun violence every week. We need common sense reform NOW. #guncontrol",
        "content_type": "post",
        "platform": "x",
        "difficulty": "hard",
        "gold_decision": "ESCALATE",
        "gold_iab_category": "IAB_CONTROVERSIAL",
        "gold_garm_category": "GARM_DEATH_INJURY",
        "gold_risk_level": "MEDIUM",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @nurse_rachel_icu, created 2018-04-12, 31K followers. Verified RN with 8 years ICU/trauma experience at Level 1 trauma center. Regularly posts medical education content and patient safety advocacy.",
        "context_layer_2": "12 community reports on this post — split evenly between gun rights groups and gun control groups flagging it. No prior reports on other content. Content pattern: 85% medical education, 15% healthcare policy advocacy. Divisive but from a credentialed, legitimate voice.",
        "notes": "Legitimate advocacy but politically divisive — escalate for brand alignment check",
    },
    {
        "content_id": "hard_002",
        "content_text": "My grandfather fought in WWII and always said 'never again.' Seeing what's happening today breaks my heart 💔",
        "content_type": "post",
        "platform": "reddit",
        "difficulty": "hard",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @never_forget_memorial, created 2016-01-27 (Holocaust Remembrance Day). Operated as a Holocaust memorial and historical education page. All content is historical remembrance, survivor stories, and anti-hate education.",
        "context_layer_2": "No community reports. No cross-platform flags. Content pattern: 100% Holocaust remembrance and WWII historical content. Partnered with Holocaust museums and educational institutions. Endorsed by Anti-Defamation League.",
        "notes": "Historical/emotional content without specific political target — safe",
    },
    {
        "content_id": "hard_003",
        "content_text": "Tried that new 'natural' cancer cure everyone's talking about instead of chemo. Week 3 update 🌿",
        "content_type": "post",
        "platform": "youtube",
        "difficulty": "hard",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_MISINFORMATION",
        "gold_garm_category": "GARM_SPAM_HARMFUL",
        "gold_risk_level": "CRITICAL",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @natural_healing_mama, created 2022-08-15, 14K followers. No medical credentials on file. Previously promoted anti-vaccination content (3 posts removed for medical misinformation). Sells unverified herbal supplements via affiliate links.",
        "context_layer_2": "47 community reports in 48 hours on this post. Cross-platform flags: shares content from known medical misinformation domains. Content pattern: escalating anti-medicine rhetoric. Multiple oncology professionals have flagged this post as dangerous.",
        "notes": "Dangerous medical misinformation — rejecting chemo for unproven cure",
    },
    {
        "content_id": "hard_004",
        "content_text": "Throwback to my wild college days 😂 Can't believe I survived that era. Grateful for growth #tbt",
        "content_type": "caption",
        "platform": "instagram",
        "difficulty": "hard",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "gold_age_rating": "ALL_AGES",
        "context_layer_1": "Account @sober_and_strong_jay, created 2020-01-01, 28K followers. Recovery and sobriety advocate. Account bio states '4 years sober.' Posts consistently use past experiences to inspire others on recovery journeys.",
        "context_layer_2": "No community reports. No cross-platform flags. Content pattern: 90% sobriety advocacy and personal growth content. Frequently tagged by recovery community organizations. Past references are always framed as growth narratives.",
        "notes": "Vague reference to past behavior without explicit content — safe",
    },
    {
        "content_id": "hard_005",
        "content_text": "The Proud Boys are the only ones standing up for real Americans. Join us. Link in bio 🇺🇸",
        "content_type": "bio",
        "platform": "reddit",
        "difficulty": "hard",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_HATE_SPEECH",
        "gold_garm_category": "GARM_TERRORISM",
        "gold_risk_level": "CRITICAL",
        "gold_age_rating": "ADULT",
        "context_layer_1": "Account @amerifirst_1776, created 2 days ago, 47 followers. Immediately began posting recruitment content upon creation. Linked to 5 previously suspended accounts via device fingerprint and IP correlation.",
        "context_layer_2": "28 community reports in 48 hours. Cross-platform flags: identical recruitment language detected on 3 extremist forums. Account is part of a coordinated ban-evasion network flagged by Trust & Safety and FBI tip line.",
        "notes": "Designated extremist group recruitment — critical reject",
    },
    {
        "content_id": "hard_006",
        "content_text": "Intermittent fasting day 47. Down 15lbs. Eating window 12pm-8pm. Not for everyone but works for me 💪",
        "content_type": "post",
        "platform": "tiktok",
        "difficulty": "hard",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "gold_age_rating": "ALL_AGES",
        "context_layer_1": "Account @rd_nutrition_facts, created 2019-06-10, 52K followers. Registered Dietitian (RD) credential verified. Shares evidence-based nutrition content and links peer-reviewed studies in most posts.",
        "context_layer_2": "No community reports. No cross-platform flags. Content pattern: 92% evidence-based nutrition education. Disclaimer language used appropriately ('not for everyone'). No affiliate supplement links or unverified health claims.",
        "notes": "Personal diet journey — factual, no misinformation, brand-safe",
    },
    {
        "content_id": "hard_007",
        "content_text": "POV: explaining to your parents why you dropped out to trade crypto full time 📈 #crypto #bitcoin",
        "content_type": "caption",
        "platform": "linkedin",
        "difficulty": "hard",
        "gold_decision": "ESCALATE",
        "gold_iab_category": "IAB_CONTROVERSIAL",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "MEDIUM",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @crypto_kid_lifestyle, age 19 (self-reported). Created 2023-06-01, 74K followers. Audience demographics: 68% ages 13-19. Promotes high-risk financial products including leveraged crypto trading and NFT drops.",
        "context_layer_2": "31 community reports for targeting minors with financial content. Cross-platform flags: SEC complaint filed for unregistered securities promotion. Content pattern: glamorizes risky financial behavior to teen audience with no risk disclosures.",
        "notes": "Crypto promotion to young audience — financial risk framing, escalate",
    },
    {
        "content_id": "hard_008",
        "content_text": "Satire: Breaking: Local man discovers that working hard actually leads to success. Scientists baffled 🙄",
        "content_type": "post",
        "platform": "x",
        "difficulty": "hard",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "gold_age_rating": "ALL_AGES",
        "context_layer_1": "Account @the_daily_snark, created 2017-09-15, 245K followers. Verified satire/comedy account. Bio explicitly states 'PARODY — nothing here is real.' Known satirist featured in comedy publications.",
        "context_layer_2": "No community reports. No cross-platform flags. Content pattern: 100% satirical commentary and parody news. Consistently labeled as satire. Platform has designated this account under its satire/parody content policy.",
        "notes": "Clearly labeled satire with no harmful content",
    },
    {
        "content_id": "hard_009",
        "content_text": "My 8-year-old asked me why some kids don't have food. Donated to the local food bank today. Small acts matter 🙏",
        "content_type": "post",
        "platform": "instagram",
        "difficulty": "hard",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "gold_age_rating": "ALL_AGES",
        "context_layer_1": "Account @kindness_starts_here, created 2019-04-22, 18K followers. Verified 501(c)(3) nonprofit account. Consistent charitable content including food drives, community events, and volunteer coordination.",
        "context_layer_2": "No community reports. No cross-platform flags. Content pattern: 100% charitable and community service content. Recognized community partner by local government. Endorsed by United Way and Feeding America chapters.",
        "notes": "Charitable/community content — highly brand-safe",
    },
    {
        "content_id": "hard_010",
        "content_text": "Leaked: internal documents show [major brand] knew about safety issues for years. Thread 🧵 1/12",
        "content_type": "post",
        "platform": "threads",
        "difficulty": "hard",
        "gold_decision": "ESCALATE",
        "gold_iab_category": "IAB_CONTROVERSIAL",
        "gold_garm_category": "GARM_SPAM_HARMFUL",
        "gold_risk_level": "HIGH",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @whistleblower_anon_x, created 2024-02-01, 920 followers. No journalistic credentials or media affiliation. Previous posts included fabricated 'leaked' documents later debunked by fact-checkers.",
        "context_layer_2": "38 community reports in 24 hours. Cross-platform flags: account shares content from known disinformation networks. Content pattern: serial 'leak' posts with no verifiable sourcing. 2 prior posts removed after legal takedown requests for defamation.",
        "notes": "Potential defamation/misinformation about a brand — escalate for legal review",
    },

    # Easy items (continued)
    {
        "content_id": "easy_011",
        "content_text": "Just finished crocheting this little mushroom amigurumi 🍄🧶 Pattern is free on my page!! #crochet #handmade #cottagecore",
        "content_type": "caption",
        "platform": "tiktok",
        "difficulty": "easy",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "gold_age_rating": "ALL_AGES",
        "context_layer_1": "Account @cozy_hooks_crafts, created 2021-04-10, 62K followers. Craft/DIY niche with brand deals from Joann Fabrics and Hobby Lobby. Zero content warnings. Verified creator.",
        "context_layer_2": "No community reports. No cross-platform flags. Content pattern: 100% crochet tutorials and craft content. High engagement from crafting communities.",
        "notes": "DIY craft content, universally brand-safe",
    },
    {
        "content_id": "easy_012",
        "content_text": "I swear I will bomb that school if they don't cancel the exam tomorrow. Not even joking. 💀",
        "content_type": "post",
        "platform": "x",
        "difficulty": "easy",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_VIOLENCE",
        "gold_garm_category": "GARM_TERRORISM",
        "gold_risk_level": "CRITICAL",
        "gold_age_rating": "MATURE",
        "context_layer_1": "Account @stressed_student99, created 2024-02-18, 89 followers. Account has 1 prior warning for violent language. No verified identity. Flagged by automated threat-detection pipeline.",
        "context_layer_2": "14 community reports within 30 minutes of posting. Cross-platform flags: none. Content pattern: mostly school complaints, but this post triggers credible-threat protocols regardless of intent.",
        "notes": "Explicit threat of violence against a school — immediate reject and report regardless of possible hyperbole",
    },
    {
        "content_id": "easy_013",
        "content_text": "SHE TOOK HER FIRST STEPS TODAY 😭😭😭 I'm not crying you're crying!! Our little girl is growing up 🥹 #babymilestone #momlife",
        "content_type": "caption",
        "platform": "youtube",
        "difficulty": "easy",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "gold_age_rating": "ALL_AGES",
        "context_layer_1": "Account @the_martinez_fam, created 2020-07-12, 34K subscribers. Family vlog channel documenting parenting milestones. Zero content warnings or strikes.",
        "context_layer_2": "No community reports. No cross-platform flags. Content pattern: 98% family milestones and parenting tips. Engagement consistent with family/parenting creator norms.",
        "notes": "Family milestone content, universally brand-safe",
    },
    {
        "content_id": "easy_014",
        "content_text": "🎉 FREE iPHONE 15 GIVEAWAY 🎉 Just follow + RT + DM me your credit card number to enter!!! Don't miss out!! #giveaway #free",
        "content_type": "bio",
        "platform": "instagram",
        "difficulty": "easy",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_ILLEGAL",
        "gold_garm_category": "GARM_SPAM_HARMFUL",
        "gold_risk_level": "HIGH",
        "gold_age_rating": "ADULT",
        "context_layer_1": "Account @free_tech_gifts_2024, created 3 days ago, 8 followers. Matches known phishing template used by credential-harvesting networks. 2 prior accounts banned for identical scam activity.",
        "context_layer_2": "47 community reports in 12 hours. Cross-platform flags: identical scam bio text detected on 9 other platforms. Network analysis links to known phishing operation flagged by platform Trust & Safety.",
        "notes": "Obvious phishing/scam soliciting financial info — immediate reject",
    },
    {
        "content_id": "easy_015",
        "content_text": "just finished reading project hail mary and omg 😩 i literally couldn't put it down. if u like sci-fi READ THIS #booktok #reading",
        "content_type": "comment",
        "platform": "tiktok",
        "difficulty": "easy",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "gold_age_rating": "ALL_AGES",
        "context_layer_1": "Account @paige_turners_books, created 2022-01-15, 19K followers. BookTok creator focused on sci-fi and fantasy reviews. Zero content warnings. Affiliate partnerships with Bookshop.org.",
        "context_layer_2": "No community reports. No cross-platform flags. Content pattern: 100% book reviews, reading challenges, and literary discussion. Active in BookTok community.",
        "notes": "Book recommendation content, clearly brand-safe",
    },

    # Medium items (continued)
    {
        "content_id": "med_011",
        "content_text": "Breaking down the hop profile of this double IPA 🍺 Notes of grapefruit, pine, and a hint of mango. ABV 8.2%. #craftbeer #beerreview",
        "content_type": "post",
        "platform": "youtube",
        "difficulty": "medium",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @hop_head_reviews, created 2018-09-20, 97K subscribers. Certified Cicerone (beer sommelier). Educational beer content with responsible drinking disclaimers in every video description.",
        "context_layer_2": "No community reports. No cross-platform flags. Content pattern: 95% craft beer education and brewery reviews. Always includes 'drink responsibly' messaging. Audience demographics: 98% over 21.",
        "notes": "Alcohol in professional/educational context with responsible messaging — most brands approve",
    },
    {
        "content_id": "med_012",
        "content_text": "8 week transformation 💪 Before & after pics!! DM me for my supplement stack, coaches are standing by 🔥 #weightloss #transformation",
        "content_type": "reel",
        "platform": "instagram",
        "difficulty": "medium",
        "gold_decision": "ESCALATE",
        "gold_iab_category": "IAB_MISINFORMATION",
        "gold_garm_category": "GARM_SPAM_HARMFUL",
        "gold_risk_level": "MEDIUM",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @fit_life_transformations, created 2022-05-11, 24K followers. Certified personal trainer (NASM). Sells supplement line via DTC storefront. No FTC complaints, but no third-party efficacy testing either.",
        "context_layer_2": "8 community reports for 'misleading health claims.' No cross-platform flags. Content pattern: 70% legitimate fitness, 30% supplement promotion. Before/after photos appear genuine but claims lack clinical backing.",
        "notes": "Borderline health marketing — credentialed but supplement claims unverified. Escalate for compliance review.",
    },
    {
        "content_id": "med_013",
        "content_text": "Use code SPIN50 for 50 free spins at CasinoRoyale.net 🎰 I just won $2K in 10 minutes lol easy money #gambling #casino #ad",
        "content_type": "post",
        "platform": "tiktok",
        "difficulty": "medium",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_GAMBLING",
        "gold_garm_category": "GARM_CRIME_HARMFUL",
        "gold_risk_level": "HIGH",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @lucky_spin_jay, created 2023-11-02, 15K followers. Audience demographics: 42% ages 13-17. Paid affiliate for unregulated offshore casino. No responsible gambling disclosures.",
        "context_layer_2": "53 community reports for promoting gambling to minors. Cross-platform flags: same affiliate code promoted on 4 other platforms. UK Gambling Commission flagged the casino site as unlicensed.",
        "notes": "Gambling promotion to underage audience from unlicensed operator — reject",
    },
    {
        "content_id": "med_014",
        "content_text": "10 years ago I came home from Afghanistan and couldn't sleep without a loaded weapon next to me. PTSD is real. If you're struggling, the VA crisis line is 988. You are not alone 🎗️",
        "content_type": "reel",
        "platform": "x",
        "difficulty": "medium",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @sgt_williams_ret, created 2019-11-11, 42K followers. Verified US Army veteran (retired). Active in veteran mental health advocacy. Partners with Wounded Warrior Project and Team Rubicon.",
        "context_layer_2": "No community reports. No cross-platform flags. Content pattern: 80% veteran mental health advocacy, 20% outdoor recreation. Weapon reference is clearly in past-tense therapeutic context with crisis resource included.",
        "notes": "Veteran mental health advocacy with crisis resources — weapon mention is therapeutic context, brand-safe",
    },
    {
        "content_id": "med_015",
        "content_text": "My CBD gummies have literally saved my sleep schedule 😴 Link to the brand I use in bio. Not medical advice! #cbd #wellness #sleep",
        "content_type": "caption",
        "platform": "instagram",
        "difficulty": "medium",
        "gold_decision": "ESCALATE",
        "gold_iab_category": "IAB_DRUGS",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "MEDIUM",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @wellness_with_wendy, created 2020-08-03, 55K followers. Wellness lifestyle creator. CBD brand is FDA-compliant (hemp-derived, <0.3% THC). Includes 'not medical advice' disclaimer.",
        "context_layer_2": "4 community reports for 'drug promotion.' No cross-platform flags. Content pattern: 75% general wellness, 25% CBD/supplement content. Disclaimer present but efficacy claims ('saved my sleep schedule') may overstate.",
        "notes": "Legal CBD product but health-adjacent claims — brand-dependent sensitivity. Escalate for policy check.",
    },
    {
        "content_id": "med_016",
        "content_text": "My kid got autism 2 weeks after the MMR shot. Exposed. Exposed. I don't care what 'studies' say I saw it with my own eyes 👁️ #truth #parenting",
        "content_type": "comment",
        "platform": "youtube",
        "difficulty": "medium",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_MISINFORMATION",
        "gold_garm_category": "GARM_SPAM_HARMFUL",
        "gold_risk_level": "HIGH",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @mama_bear_truth, created 2021-03-14, 7.8K followers. Posts anti-vaccination content weekly. No medical credentials. Shares content from sites flagged by WHO as vaccine misinformation sources.",
        "context_layer_2": "72 community reports for medical misinformation. Cross-platform flags: shares debunked vaccine-autism content on 3 other platforms. Content pattern: 60% anti-vaccine, 40% general parenting. Platform has added misinformation labels to 5 prior posts.",
        "notes": "Debunked vaccine-autism misinformation — dangerous public health content, reject",
    },
    {
        "content_id": "med_017",
        "content_text": "New episode dropping tmrw 🎙️ We break down the psychology behind the Dahmer case. Why do serial killers escalate? Link in bio #truecrime #podcast",
        "content_type": "caption",
        "platform": "tiktok",
        "difficulty": "medium",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @criminal_minds_pod, created 2020-02-28, 310K followers. True-crime podcast hosted by a forensic psychologist (Ph.D.) and a former FBI behavioral analyst. Content approaches cases from an educational/psychological lens.",
        "context_layer_2": "No community reports. No cross-platform flags. Content pattern: 100% educational true-crime analysis with expert commentary. No gratuitous violence or victim exploitation. Partnered with victim advocacy nonprofits.",
        "notes": "True-crime content in educational context by credentialed hosts — brand-safe for most advertisers",
    },
    {
        "content_id": "med_018",
        "content_text": "lmaooo whoever made this meme of the senator falling asleep during the hearing deserves an award 😂😂 our tax dollars at work #politics #meme",
        "content_type": "post",
        "platform": "x",
        "difficulty": "medium",
        "gold_decision": "ESCALATE",
        "gold_iab_category": "IAB_CONTROVERSIAL",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "MEDIUM",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @dank_political_memes, created 2019-10-22, 180K followers. Political humor account with bipartisan mocking — targets all parties. No affiliation with political organizations. Zero content warnings.",
        "context_layer_2": "6 community reports on this post — from supporters of the senator. No prior reports on other content. Content pattern: 85% political humor memes, 15% current events commentary. Humor is pointed but non-hateful.",
        "notes": "Political humor — not hateful but brand-sensitivity varies by advertiser. Escalate for alignment.",
    },

    # Hard items (continued)
    {
        "content_id": "hard_011",
        "content_text": "Took my kids to Drag Queen Story Hour at the library today 📚🌈 They LOVED it. Representation matters. If you don't like it, keep scrolling ✌️ #lgbtq #pride #family",
        "content_type": "post",
        "platform": "instagram",
        "difficulty": "hard",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "gold_age_rating": "ALL_AGES",
        "context_layer_1": "Account @proud_ally_parent, created 2019-06-01, 25K followers. LGBTQ+ ally and parenting blogger. Partners with PFLAG and local library systems. Zero content warnings or strikes.",
        "context_layer_2": "44 community reports — bulk-reported by coordinated anti-LGBTQ+ campaign (flagged by Trust & Safety as brigading). No organic reports. Content pattern: 70% inclusive parenting, 30% family activities. Library event is publicly listed and family-oriented.",
        "notes": "LGBTQ+ inclusive family content — reports are coordinated brigading, not organic concern. Content is safe.",
    },
    {
        "content_id": "hard_012",
        "content_text": "We need to secure a future for our people. The great replacement is real — look at the demographics. Stay based, kings 👑 #tradition #heritage",
        "content_type": "post",
        "platform": "x",
        "difficulty": "hard",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_HATE_SPEECH",
        "gold_garm_category": "GARM_HATE_SPEECH",
        "gold_risk_level": "CRITICAL",
        "gold_age_rating": "ADULT",
        "context_layer_1": "Account @heritage_defender_eu, created 2023-08-14, 3.2K followers. Uses coded white-nationalist language ('great replacement,' 'based,' 'kings'). Linked to 3 previously banned accounts via network analysis.",
        "context_layer_2": "22 community reports. Cross-platform flags: identical rhetoric detected on known white-supremacist forums. Content pattern: 100% ethno-nationalist content using sanitized language to evade keyword filters. ADL has cataloged these phrases as hate-movement terminology.",
        "notes": "Coded white-nationalist rhetoric — 'great replacement' is a recognized hate conspiracy theory despite surface-level neutral phrasing",
    },
    {
        "content_id": "hard_013",
        "content_text": "5 years ago I was moving weight on these same blocks. Trapping every night, no sleep, paranoid 24/7. Today I run a legit trucking company 🚛 If I can change so can you. #redemption #motivation",
        "content_type": "caption",
        "platform": "tiktok",
        "difficulty": "hard",
        "gold_decision": "ESCALATE",
        "gold_iab_category": "IAB_DRUGS",
        "gold_garm_category": "GARM_CRIME_HARMFUL",
        "gold_risk_level": "MEDIUM",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @ceo_from_the_block, created 2021-09-15, 410K followers. Verified business owner (DOT-registered trucking company). Featured in local news for community mentorship programs. No active criminal record.",
        "context_layer_2": "9 community reports for 'drug content.' No cross-platform flags. Content pattern: 80% motivational/business content, 15% community outreach, 5% past-life references. All drug references are clearly past-tense and framed as cautionary/redemptive.",
        "notes": "Redemption narrative with explicit drug-dealing references — past-tense and inspirational but language may trigger brand policies. Escalate for review.",
    },
    {
        "content_id": "hard_014",
        "content_text": "Aleppo, 2016. This image haunts me. A child pulled from rubble, covered in dust and blood. We cannot look away. 📸 #photojournalism #syria #pressphoto",
        "content_type": "caption",
        "platform": "instagram",
        "difficulty": "hard",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_DEATH_INJURY",
        "gold_risk_level": "MEDIUM",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @lens_of_truth_photog, created 2014-03-08, 290K followers. Pulitzer Prize-winning photojournalist. Accredited press credentials with Reuters and AP. Work exhibited at International Center of Photography.",
        "context_layer_2": "18 community reports for 'graphic content.' No cross-platform flags. Content pattern: 100% documentary photojournalism. Platform has exempted account under newsworthiness policy. Images comply with platform's graphic-content-with-context guidelines.",
        "notes": "Professional photojournalism with newsworthy context — graphic but protected under press/newsworthiness exemptions. Brand-safe for news-adjacent advertisers.",
    },
    {
        "content_id": "hard_015",
        "content_text": "Boss babe 💅 CEO of my own destiny. Tired of the 9-5? Join my team and start earning $10K/month from your phone 📱 DM 'FREEDOM' to start #girlboss #entrepreneur #financialfreedom",
        "content_type": "bio",
        "platform": "linkedin",
        "difficulty": "hard",
        "gold_decision": "REJECT",
        "gold_iab_category": "IAB_MISINFORMATION",
        "gold_garm_category": "GARM_SPAM_HARMFUL",
        "gold_risk_level": "HIGH",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @diamond_level_hun, created 2022-07-20, 8.4K followers. Recruiter for MLM company under FTC investigation. Income claims violate FTC guidelines — actual median participant earnings: $47/month.",
        "context_layer_2": "38 community reports for 'misleading business opportunity.' Cross-platform flags: identical recruitment language detected across 6 platforms. Network analysis links to pyramid-scheme recruitment funnel with 200+ downstream accounts.",
        "notes": "MLM recruitment with deceptive income claims disguised as female empowerment — predatory marketing, reject",
    },
    {
        "content_id": "hard_016",
        "content_text": "tw // self harm. 2 years clean today. i never thought i'd make it this far. if you're in that dark place pls reach out — crisis text line: text HOME to 741741 💛 #recovery #mentalhealth",
        "content_type": "post",
        "platform": "x",
        "difficulty": "hard",
        "gold_decision": "APPROVE",
        "gold_iab_category": "IAB_SAFE",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "LOW",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @healing_not_linear, created 2021-05-16, 14K followers. Mental health recovery advocate. Content consistently includes trigger warnings and crisis resources. Partnered with Crisis Text Line and NAMI.",
        "context_layer_2": "3 community reports for 'self-harm content.' No cross-platform flags. Content pattern: 95% recovery advocacy with appropriate trigger warnings and crisis hotline resources. Platform mental-health team has reviewed and approved content under recovery-narrative policy.",
        "notes": "Self-harm recovery narrative with trigger warnings and crisis resources — protective content that aids at-risk users. Approve under recovery-content policy.",
    },
    {
        "content_id": "hard_017",
        "content_text": "As an Israeli and Palestinian peace activist, I've sat with families on both sides who've lost children. Peace isn't weakness — it's the hardest fight there is. 🕊️ #peace #coexistence",
        "content_type": "comment",
        "platform": "threads",
        "difficulty": "hard",
        "gold_decision": "ESCALATE",
        "gold_iab_category": "IAB_CONTROVERSIAL",
        "gold_garm_category": "GARM_SAFE",
        "gold_risk_level": "MEDIUM",
        "gold_age_rating": "TEEN",
        "context_layer_1": "Account @bridges_not_walls_org, created 2017-01-20, 67K followers. Registered nonprofit peace organization. Board includes members from both Israeli and Palestinian communities. Endorsed by Nobel Peace laureates.",
        "context_layer_2": "55 community reports — split between pro-Israel and pro-Palestinian groups flagging it as 'propaganda.' Content pattern: 100% peace-building and coexistence advocacy. No hateful content or one-sided framing. Reports are from opposing partisan groups, not organic safety concerns.",
        "notes": "Legitimate peace advocacy on highly sensitive geopolitical topic — content is constructive but topic is brand-sensitive. Escalate for advertiser alignment.",
    },
]

# Index by content_id for O(1) lookup
CONTENT_INDEX: Dict[str, Dict[str, Any]] = {
    item["content_id"]: item for item in CONTENT_ITEMS
}
